apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: coredns-vpa
  namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       coredns
  updatePolicy:
    updateMode: "Off"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: coredns-role-vpa-security-perimeter
rules:
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers", "verticalpodautoscalercheckpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coredns-rolebinding-vpa-security-perimeter
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
roleRef:
  kind: Role
  name: coredns-role-vpa-security-perimeter
  apiGroup: rbac.authorization.k8s.io