apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 11s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 169.254.169.253 {
          max_fails 0 
        }
        cache 30
        loop
        reload
        loadbalance
        template ANY AAAA {
          rcode NOERROR
       }
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system